os: linux
dist: bionic
language: java

### Maven basic build ###
jobs:
  include:
    # 1. Test
    - stage: Test
      jdk: openjdk8
    - jdk: openjdk11

    # 2. Deploy
    - stage: Deploy
      if: |
        fork == false && type != pull_request
      # Use the minimal supported version (this assures that no version-specific bytecode gets generated)
      jdk: openjdk8
      before_deploy: ./.travis/scripts/import_code_signing_keys.sh
      # Use deployment strategy corresponding to current
      deploy:
        # Deploy snapshot to Sonatype OSSRH
        - provider: script
          edge: true
          script: ./.travis/scripts/maven_deploy.sh
          on:
            branch: development
            condition: "\"$(./.travis/scripts/get_version.sh)\" == *-SNAPSHOT"

        # Deploy release to Maven Central
        - provider: script
          edge: true
          script: ./.travis/scripts/maven_deploy.sh release
          on:
            branch: master
            tags: true
            condition: "\"$(./.travis/scripts/get_version.sh)\" != *-SNAPSHOT"

cache:
  directories:
    - ~/.m2/repository
